[project]
name = "lyricardsbot"
version = "0.1.0"
description = "Telegram bot for creating song lyrics card images."
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "aiogram>=3.23.0",
    "asyncer>=0.0.11",
    "fuzzywuzzy>=0.18.0",
    "httpx>=0.28.1",
    "lyricsgenius>=3.7.5",
    "orjson>=3.11.5",
    "pillow>=12.0.0",
    "pydantic>=2.12.5",
    "python-decouple>=3.8",
    "python-levenshtein>=0.27.3",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "fuzzywuzzy-stubs>=0.0.1",
    "isort>=7.0.0",
    "mypy>=1.19.1",
    "python-decouple-stubs>=3.8.0.4",
    "ruff>=0.14.10",
]


[tool.black]
line-length = 120


[tool.flake8]
exclude = [".venv", "env", "venv", ".git", "__pycache__", "docs", "build", "dist"]
max-line-length = 120
ignore = ["E266", "W503"]
